#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only

import argparse
import fcntl
from functools import partial
import logging
logger = logging.getLogger(__name__)
import os
import sys
import time
import traceback

import whipper
import whipper.common
import whipper.common.config
import whipper.command.main
import whipper.program.utils

try:
    import pyudev
    pyudev_context = pyudev.Context()
    device_monitor = pyudev.Monitor.from_netlink(pyudev_context)
except ModuleNotFoundError:
    pyudev = None
    device_monitor = None

DRIVE_DELAY = 10


class BugNotificationFilter(logging.Filter):
    bug234_msg_shown = False

    def filter(self, record):
        if record.msg == "because of a cd-paranoia upstream bug whipper may fail to work correctly when using offset values > 587 (current value: %d) and print warnings like this: 'file size 0 did not match expected size'. For more details please check the following issues: https://github.com/whipper-team/whipper/issues/234 and https://github.com/rocky/libcdio-paranoia/issues/14":
            if not self.bug234_msg_shown:
                self.bug234_msg_shown = True
                return True
            else:
                return False

cdparanoiaLogger = logging.getLogger('whipper.program.cdparanoia')
cdparanoiaLogger.addFilter(BugNotificationFilter())


def getConfig():
    config = dict()
    parser = whipper.common.config.Config()._parser

    for section in parser.sections():
        config[section] = dict(parser.items(section))

    return config


def getDevices():
    devices = whipper.common.drive.getAllDevicePaths()
    if not devices:
        msg = 'No CD-DA drives found!'
        logger.critical(msg)
        raise IOError(msg)
    return devices


def getDriveStatus(device):
    # From uapi/linux/cdrom.h:
    CDROM_DRIVE_STATUS = 0x5326
    CDS = {
        0: 'CDS_NO_INFO',
        1: 'CDS_NO_DISC',
        2: 'CDS_TRAY_OPEN',
        3: 'CDS_DRIVE_NOT_READY',
        4: 'CDS_DISC_OK',
    }
    try:
        fd = os.open(device, os.O_NONBLOCK)
        status = CDS[fcntl.ioctl(fd, CDROM_DRIVE_STATUS)]
        os.close(fd)
    except Exception as e:
        return traceback.format_exception(e)
    return status


def getRealDevices(selected_device=None):
    devices = [
        os.path.realpath(device)
            for device in getDevices()
    ]
    if selected_device is not None:
        devices = [
            device
                for device in devices
                    if device == os.path.realpath(selected_device)
        ]
        if not devices:
            msg = f"CD-DA device '{selected_device}' not found!"
            logger.critical(msg)
            raise IOError(msg)
    return [
        device
            for device in devices
                if os.path.exists(device)
    ]


def main():
    prog_name = "whipper"

    # Trace the config
    logger.info(f"whipper: {whipper.__file__}")
    logger.info(f"config: {getConfig()}")

    # Parse the arguments
    parser = argparse.ArgumentParser()
    argv = sys.argv[1:]

    devices = getDevices()
    parser.add_argument('-d', '--device',
        action="store",
        dest="device",
        default=None,
        help=f"CD-DA device, e.g. '{devices[0]}'")

    options = parser.parse_args(argv, namespace=None)

    # Select the CD-DA device
    devices = getRealDevices(options.device)
    if len(devices) == 1:
        device = devices[0]
        options.device = device
    else:
        msg = f"CD-DA devices found: {devices}\nPlease select one through the '--device' option."
        logger.critical(msg)
        raise IOError(msg)
    if device_monitor:
        device_udev = pyudev.Devices.from_device_file(pyudev_context, device)
        device_monitor.filter_by(subsystem=device_udev.subsystem, device_type=device_udev.device_type)
    logger.info(f"device: '{device}', device monitor: {type(device_monitor)}")

    # (Almost) infinite loop: exit if the device is disconnected
    status = None
    while device in getRealDevices():
        # Check if a disc is in the drive
        previous_status = status
        status = getDriveStatus(device)
        if status != 'CDS_DISC_OK':
            if status != previous_status:
                if status[:4] == 'CDS_':
                    msg = f"{device}: {status}"
                    logger.info(msg)
                else:
                    msg = f"Can't get drive status for '{device}':\n{status}"
                    logger.warn(msg)
            time.sleep(DRIVE_DELAY)
            continue

        # Rip the current disc
        try:
            rip = whipper.command.main.Whipper(['cd', 'rip'], prog_name=prog_name, opts=options)
            ret = rip.do()
        except Exception as e:
            msg = '\t'.join(traceback.format_exception(e))
            logger.error(msg)

        # Eject the current disc
        whipper.program.utils.eject_device(device)
        time.sleep(DRIVE_DELAY)

        # Ask for another disc
        input_val = None
        while input_val != '':
            if device_monitor:
                # TODO async monitor + timeout on input?
                #input_val = input("Insert a new disc, or type 'q' to quit: ")
                print("Insert a new disc, or use [Ctrl]+[C] to quit: ")
                for event_device in iter(partial(device_monitor.poll, 60), None):
                    if event_device == device_udev:
                        input_val = ''
                        msg = f"udev: {event_device.action} detected on '{device}'"
                        logger.warning(msg)
                        break
            else:
                input_val = input("Insert a new disc and press [Enter], or type 'q' to quit: ")

            if input_val:
                if input_val.lower() == 'q':
                    sys.exit(0)

    print(f"Device '{device}' was disconnected, quitting")

main()

